### ISSUE TITLE
English section needs an update

### ISSUE THREAD

**Issue by TiTo-418** [savethewools/Forum-Post#1]
Links
Times
Maps section has incorrect format

**Comment by TiTo-418** [comment]
Ups

**Comment by dentmaged** [comment]
I'll do it in a second

**Comment by TiTo-418** [comment]
@RubeVi Fijate si podes hacerlo

**Comment by TiTo-418** [comment]
@RubeVi Deberias verlo un poco antes de mergearlo http://prntscr.com/722b9k
